name: python-clean_data
on:
  workflow_dispatch

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: check version of python
      run: |
        python --version
        pip install pandas
    - name: checkout code
      uses: actions/checkout@v4